version: '3.7'

services:
  node1:
    container_name: besu-node1
    image: hyperledger/besu:25.8.0
    ports:
      - "8545:8545" # RPC
    volumes:
      - ./Node-1/data:/var/lib/besu/data
      - ./genesis.json:/var/lib/besu/genesis.json
    networks:
      besu-network:
        ipv4_address: 172.20.0.2
    command: >
      --data-path=/var/lib/besu/data
      --genesis-file=/var/lib/besu/genesis.json
      --node-private-key-file=/var/lib/besu/data/key
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,IBFT,ADMIN
      --host-allowlist="*"
      --rpc-http-cors-origins="*"
      --profile=ENTERPRISE
      --rpc-http-host=0.0.0.0
      --p2p-host=172.20.0.2
      --rpc-http-port=8545
      --network-id=1337
      --min-gas-price=0
      --target-gas-limit=1000000000
      --tx-pool-max-size=50000
      --revert-reason-enabled=true

  node2:
    container_name: besu-node2
    image: hyperledger/besu:25.8.0
    ports:
      - "8546:8546"
    volumes:
      - ./Node-2/data:/var/lib/besu/data
      - ./genesis.json:/var/lib/besu/genesis.json
    depends_on:
      - node1
    networks:
      besu-network:
        ipv4_address: 172.20.0.3
    command: >
      --data-path=/var/lib/besu/data
      --genesis-file=/var/lib/besu/genesis.json
      --node-private-key-file=/var/lib/besu/data/key
      --bootnodes=enode://35ffa7fa5a835a0459915f9bb074b2db24068e5fa3a62e73e7240158f778c074373f66f36a5cca51139048e4ee7e0d36bd589d5ac53c8446dd6ef04cecac2e09@172.20.0.2:30303
      --p2p-port=30304
      --rpc-http-enabled=true
      --rpc-http-api=ETH,NET,IBFT,WEB3,DEBUG,ADMIN,TXPOOL
      --host-allowlist="*"
      --rpc-http-cors-origins="*"
      --rpc-http-port=8546
      --profile=ENTERPRISE
      --rpc-http-host=0.0.0.0
      --p2p-host=172.20.0.3
      --network-id=1337
      --min-gas-price=0
      --target-gas-limit=1000000000
      --tx-pool-max-size=50000
      --revert-reason-enabled=true

  node3:
    container_name: besu-node3
    image: hyperledger/besu:25.8.0
    ports:
      - "8547:8547"
    volumes:
      - ./Node-3/data:/var/lib/besu/data
      - ./genesis.json:/var/lib/besu/genesis.json
    depends_on:
      - node1
    networks:
      besu-network:
        ipv4_address: 172.20.0.4
    command: >
      --data-path=/var/lib/besu/data
      --genesis-file=/var/lib/besu/genesis.json
      --node-private-key-file=/var/lib/besu/data/key
      --bootnodes=enode://35ffa7fa5a835a0459915f9bb074b2db24068e5fa3a62e73e7240158f778c074373f66f36a5cca51139048e4ee7e0d36bd589d5ac53c8446dd6ef04cecac2e09@172.20.0.2:30303
      --p2p-port=30305
      --rpc-http-enabled=true
      --rpc-http-api=ETH,NET,IBFT,WEB3,DEBUG,ADMIN,TXPOOL
      --host-allowlist="*"
      --rpc-http-cors-origins="*"
      --rpc-http-port=8547
      --profile=ENTERPRISE
      --rpc-http-host=0.0.0.0
      --p2p-host=172.20.0.4
      --network-id=1337
      --min-gas-price=0
      --target-gas-limit=1000000000
      --tx-pool-max-size=50000
      --revert-reason-enabled=true

  node4:
    container_name: besu-node4
    image: hyperledger/besu:25.8.0
    ports:
      - "8548:8548"
    volumes:
      - ./Node-4/data:/var/lib/besu/data
      - ./genesis.json:/var/lib/besu/genesis.json
    depends_on:
      - node1
    networks:
      besu-network:
        ipv4_address: 172.20.0.5
    command: >
      --data-path=/var/lib/besu/data
      --genesis-file=/var/lib/besu/genesis.json
      --node-private-key-file=/var/lib/besu/data/key
      --bootnodes=enode://35ffa7fa5a835a0459915f9bb074b2db24068e5fa3a62e73e7240158f778c074373f66f36a5cca51139048e4ee7e0d36bd589d5ac53c8446dd6ef04cecac2e09@172.20.0.2:30303
      --p2p-port=30306
      --rpc-http-enabled=true
      --rpc-http-api=ETH,NET,IBFT,WEB3,DEBUG,ADMIN,TXPOOL
      --host-allowlist="*"
      --rpc-http-cors-origins="*"
      --rpc-http-port=8548
      --profile=ENTERPRISE
      --rpc-http-host=0.0.0.0
      --p2p-host=172.20.0.5
      --network-id=1337
      --min-gas-price=0
      --target-gas-limit=1000000000
      --tx-pool-max-size=50000
      --revert-reason-enabled=true
      
  explorer:
    container_name: blockchain-explorer
    image: consensys/quorum-explorer:latest
    ports:
      - "25000:25000/tcp"
    networks:
      besu-network:
        ipv4_address: 172.20.0.6
    environment:
      - QE_CONFIG_PATH=/app/config.json
      - NODE_ENV=production
      - DISABLE_AUTH=true
      - NEXTAUTH_URL=http://localhost:25000
      - NEXTAUTH_URL_INTERNAL=http://localhost:25000
    volumes:
      - ./explorer-config.json:/app/config.json
    restart: unless-stopped

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16