services:
  quorum-explorer:
    container_name: blockchain-explorer
    image: consensys/quorum-explorer:latest
    ports:
      - "25000:25000/tcp"
    networks:
      ibft-network_besu-network:
        ipv4_address: 172.20.0.6
    environment:
      - QE_CONFIG_PATH=/app/config.json
      - NODE_ENV=production
      - DISABLE_AUTH=true
      - NEXTAUTH_URL=http://localhost:25000
      - NEXTAUTH_URL_INTERNAL=http://localhost:25000
    volumes:
      - ./explorer-config.json:/app/config.json
    restart: unless-stopped

networks:
  ibft-network_besu-network:
    external: true